name: Deploy to Workers Prod

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        
      - name: Install Wrangler
        run: sudo npm i @cloudflare/wrangler -g
      - name: Build index.js
        run: python3 ./build.py 
      - name: commit new index.js
        run: git add index.js && git commit -m "updated with github actions" && git push
      - name: config wrangler
        run: CF_API_TOKEN=${{ secrets.CF_API_TOKEN }} wrangler publish